################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# footer content
footer_content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua."


################################### NL language #####################################
[Nl]
languageName = "Nl"
languageCode = "nl-nl"
contentDir = "content/nederlands"
weight = 2
# footer content
footer_content = "Hier komt nederlandse tekst"